# Generated by Django 6.0.4 on 2026-05-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='message',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
